In [50]:
import numpy as np
import pandas as pd


print(f"NumPy Version --> {np.__version__}")
print(f"Pandas Version --> {pd.__version__}")


print("\nAll libraries imported successfully")

NumPy Version --> 1.26.4
Pandas Version --> 2.3.3

All libraries imported successfully

In [51]:
data = pd.read_csv("../Airbnb/Airbnb_Open_Data.csv")

C:\Users\Ramesh\AppData\Local\Temp\ipykernel_2420\3874470155.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../Airbnb/Airbnb_Open_Data.csv")

In [52]:
data.head(5)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [53]:
print(f"Shape: {data.shape}")
print(f"\nColumns: {data.columns}")

Shape: (102599, 26)

Columns: Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

#### Delete Redundant Columns
#### Rename Columns
#### Drop Duplicates
#### Remove NaN Values from Dataset
#### Clean Individual Columns
#### Check for further transformations

# Deleting Redundant Columns

In [55]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [56]:
columns_to_drop = ['id',  'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

data.drop(columns=columns_to_drop, inplace=True)
print(data.shape)

(102599, 19)

# Renaming Columns

In [57]:
data.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [58]:
new_names = []
for col in data.columns:
    new_names.append(col.lower().capitalize())

new_names

['Name',
 'Host id',
 'Host_identity_verified',
 'Host name',
 'Neighbourhood group',
 'Neighbourhood',
 'Lat',
 'Long',
 'Country',
 'Country code',
 'Instant_bookable',
 'Cancellation_policy',
 'Room type',
 'Construction year',
 'Price',
 'Service fee',
 'Minimum nights',
 'Number of reviews',
 'Last review']

In [59]:
data.columns = new_names
data.columns

Index(['Name', 'Host id', 'Host_identity_verified', 'Host name',
       'Neighbourhood group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country code', 'Instant_bookable', 'Cancellation_policy', 'Room type',
       'Construction year', 'Price', 'Service fee', 'Minimum nights',
       'Number of reviews', 'Last review'],
      dtype='object')

# Dropping Duplicates

In [60]:
data.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [61]:
data.shape

(102599, 19)

In [62]:
data.drop_duplicates(inplace = True)
data.shape

(102058, 19)

# Removing NaN values

In [63]:
data.isna().sum()

Name                        250
Host id                       0
Host_identity_verified      289
Host name                   404
Neighbourhood group          29
Neighbourhood                16
Lat                           8
Long                          8
Country                     532
Country code                131
Instant_bookable            105
Cancellation_policy          76
Room type                     0
Construction year           214
Price                       247
Service fee                 273
Minimum nights              400
Number of reviews           183
Last review               15832
dtype: int64

In [64]:
# Dropping Last Review Column
data.drop(columns = ["Last review"],inplace = True)

In [65]:
data.isna().sum()

Name                      250
Host id                     0
Host_identity_verified    289
Host name                 404
Neighbourhood group        29
Neighbourhood              16
Lat                         8
Long                        8
Country                   532
Country code              131
Instant_bookable          105
Cancellation_policy        76
Room type                   0
Construction year         214
Price                     247
Service fee               273
Minimum nights            400
Number of reviews         183
dtype: int64

In [66]:
data.dropna(inplace = True)
data.isna().sum()

Name                      0
Host id                   0
Host_identity_verified    0
Host name                 0
Neighbourhood group       0
Neighbourhood             0
Lat                       0
Long                      0
Country                   0
Country code              0
Instant_bookable          0
Cancellation_policy       0
Room type                 0
Construction year         0
Price                     0
Service fee               0
Minimum nights            0
Number of reviews         0
dtype: int64

In [67]:
data.shape

(99342, 18)

# Clean Individual Columns

In [68]:
data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
82458,"Harlem 1 BR apartment w/ washer&dryer, near su...",79124385598,unconfirmed,Yve,Manhattan,Harlem,40.81246,-73.94906,United States,US,True,moderate,Entire home/apt,2015.0,$938,$188,2.0,64.0
69143,"Large, Neat & Spacious One BDR UWS Apartment!",27813127757,unconfirmed,Kat,Manhattan,Upper West Side,40.78169,-73.97881,United States,US,True,moderate,Entire home/apt,2017.0,$834,$167,2.0,4.0
93384,Bright & Quiet Minutes from Washington Square ...,89538635404,unconfirmed,Alistair,Manhattan,NoHo,40.72822,-73.99239,United States,US,False,moderate,Entire home/apt,2012.0,$936,$187,7.0,12.0
16013,Huge + Cozy East Williamsburg Room,65479019319,unconfirmed,Caroline,Brooklyn,Bushwick,40.70290,-73.92960,United States,US,False,flexible,Private room,2022.0,$455,$91,3.0,5.0
48789,Downtown NYC Convenient Private Room,93422577706,verified,Xiao,Manhattan,Lower East Side,40.71466,-73.98676,United States,US,True,strict,Private room,2008.0,$688,$138,1.0,0.0
61198,Sharon's Home Away from Home,8482543498,verified,Sharon,Queens,Cambria Heights,40.68465,-73.74687,United States,US,False,moderate,Entire home/apt,2015.0,$498,$100,2.0,12.0
92038,"Warm home in Woodside, Queens.",41467662615,verified,Giani,Queens,Maspeth,40.73443,-73.89635,United States,US,True,strict,Private room,2021.0,$401,$80,1.0,7.0
83262,"Quiet/Modern Triplex loft, steps to prospect p...",95526389790,verified,Andrea,Brooklyn,Prospect Heights,40.67729,-73.96535,United States,US,False,flexible,Private room,2021.0,$56,$11,5.0,37.0
2842,SUNNY STUDIO MIDTOWN EAST W/DOORMAN,35907276367,unconfirmed,Maria,Manhattan,Midtown,40.75290,-73.97094,United States,US,True,flexible,Entire home/apt,2016.0,$59,$12,5.0,116.0
7868,Boarding Room-style mini apartment/Harlem Oasis,88765206754,verified,Kiela,Manhattan,Harlem,40.80991,-73.94058,United States,US,False,flexible,Entire home/apt,2020.0,$90,$18,2.0,18.0

In [69]:
## Host_identity_verified column values will be converted to uppercase 
data["Host_identity_verified"] = data["Host_identity_verified"].str.upper()
data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
46131,Quiet garden suite w/ kitchenette & backyard p...,68936244618,UNCONFIRMED,Steve & Stephanie,Brooklyn,Crown Heights,40.67165,-73.95644,United States,US,False,moderate,Entire home/apt,2004.0,$987,$197,3.0,3.0
72846,Brooklyn Basement Apartment,43765891005,UNCONFIRMED,Mike,Brooklyn,Kensington,40.64291,-73.97928,United States,US,False,flexible,Entire home/apt,2012.0,$382,$76,1.0,1.0
100601,Light filled private room in Red Hook!,18263707134,VERIFIED,Mattia,Brooklyn,Red Hook,40.67414,-74.00707,United States,US,True,strict,Private room,2006.0,$804,$161,4.0,4.0
41690,Sofa-bed in apartment in Astoria! Near Manhattan!,27076435660,VERIFIED,Lucca & Paula,Queens,Astoria,40.76466,-73.91274,United States,US,True,strict,Shared room,2018.0,"$1,124",$225,1.0,17.0
3116,Beautiful 1BR in East Village!,57941471257,VERIFIED,Camille,Manhattan,East Village,40.72969,-73.98151,United States,US,False,strict,Entire home/apt,2019.0,$551,$110,5.0,9.0
66731,Charming Bedroom in E. Williamsburg by Graham L,23081915166,VERIFIED,Jean,Brooklyn,Williamsburg,40.71558,-73.93974,United States,US,False,strict,Private room,2022.0,$387,$77,10.0,15.0
12289,Charming PreWar Bedroom in Flatbush,22367469814,VERIFIED,Jenny,Brooklyn,East Flatbush,40.65343,-73.95175,United States,US,False,strict,Private room,2009.0,$883,$177,3.0,0.0
100286,"1 Bedroom in the Heart of The Upper East Side, NY",94828639346,UNCONFIRMED,Joe,Manhattan,Upper East Side,40.77320,-73.95857,United States,US,True,strict,Private room,2020.0,"$1,167",$233,2.0,14.0
3219,Adorable 1BD Home with view of NYC,2047976432,UNCONFIRMED,Lauren,Queens,Astoria,40.77453,-73.92833,United States,US,True,moderate,Entire home/apt,2006.0,"$1,178",$236,4.0,17.0
46980,Charming Moroccan style Rooms on Upper West Side,59964005253,UNCONFIRMED,Hajar,Manhattan,Upper West Side,40.78642,-73.97723,United States,US,False,strict,Private room,2011.0,$804,$161,3.0,0.0

In [70]:
## Converting Boolean Columns into Binary Columns
data["Instant_bookable"] = data["Instant_bookable"].map({True:1,False:0})
data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
29858,"Entire Apt Spacious & Chic-Near JFK, Subway & ...",52513129116,UNCONFIRMED,Pebel,Queens,Woodhaven,40.69665,-73.85114,United States,US,1,moderate,Entire home/apt,2003.0,$445,$89,4.0,1.0
6137,Heart of the East Village- Best Loc,81515543769,VERIFIED,Chris,Manhattan,East Village,40.72724,-73.98639,United States,US,1,moderate,Entire home/apt,2015.0,$705,$141,1.0,2.0
68144,Huge private bedroom in the heart of Manhattan,94794911706,VERIFIED,Uly,Manhattan,Upper East Side,40.76528,-73.96218,United States,US,0,strict,Private room,2021.0,$694,$139,2.0,57.0
9788,Large light-filled master bedroom.,91819901503,VERIFIED,Julia,Manhattan,Harlem,40.80313,-73.95742,United States,US,0,strict,Private room,2022.0,$699,$140,2.0,1.0
21042,"Sunny room in Sunset Park, Brooklyn",33053507190,UNCONFIRMED,Keisuke,Brooklyn,Sunset Park,40.64364,-74.01206,United States,US,1,moderate,Private room,2020.0,$433,$87,7.0,0.0
82045,Brooklyn Basement,66421644817,VERIFIED,Kinser,Brooklyn,Bedford-Stuyvesant,40.68322,-73.91702,United States,US,0,flexible,Shared room,2018.0,$309,$62,1.0,1.0
5668,Large 1 Bedroom apartment with office room.,52496050669,UNCONFIRMED,Patrick,Brooklyn,Kensington,40.64449,-73.97238,United States,US,0,flexible,Private room,2009.0,$229,$46,3.0,8.0
7486,Cozy bedroom in Brooklyn Sunsetpark,12674207147,VERIFIED,Sam,Brooklyn,Sunset Park,40.65118,-74.00842,United States,US,0,flexible,Private room,2011.0,"$1,035",$207,2.0,0.0
79389,Gorgeous One Bedroom in the Heart of Chelsea,87015162766,VERIFIED,Cari,Manhattan,Chelsea,40.74123,-73.99522,United States,US,0,strict,Entire home/apt,2015.0,$518,$104,4.0,45.0
91590,Brooklyn Cave in the Neighb,18148079939,UNCONFIRMED,Avon,Brooklyn,Canarsie,40.64458,-73.90285,United States,US,0,flexible,Entire home/apt,2011.0,"$1,033",$207,2.0,68.0

In [71]:
# Removing Dollar Symbols
data["Service fee"] = data["Service fee"].str.replace("$","")
data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
90670,You Deserve The Royal Treatment.,76047414115,VERIFIED,Percy,Bronx,Norwood,40.87692,-73.87427,United States,US,0,moderate,Entire home/apt,2004.0,"$1,090",218,5.0,0.0
10197,Brooklyn Brownstone Beautiful,38005625190,UNCONFIRMED,Julia,Brooklyn,Clinton Hill,40.68332,-73.96271,United States,US,1,moderate,Entire home/apt,2018.0,$161,32,6.0,35.0
2688,Spacious very High ceiling place !,43887734729,VERIFIED,Celin,Manhattan,Harlem,40.82407,-73.94434,United States,US,1,flexible,Private room,2022.0,$715,143,7.0,40.0
53471,Entire Studio Flat in Prospect Lefferts-Garden...,169042877,VERIFIED,Johnny,Brooklyn,Prospect-Lefferts Gardens,40.66296,-73.95361,United States,US,0,strict,Entire home/apt,2013.0,$936,187,5.0,27.0
29562,"Clean, Large 2 Bedroom Duplex Apartment w/ Patio",45147215730,VERIFIED,Narina,Manhattan,East Harlem,40.80954,-73.93934,United States,US,0,moderate,Entire home/apt,2006.0,"$1,015",203,4.0,8.0
55395,Lovely renovated 3bd/3 bathroom apartment nyc,85932331787,UNCONFIRMED,Johanna,Brooklyn,Bedford-Stuyvesant,40.69503,-73.94025,United States,US,0,moderate,Entire home/apt,2011.0,$505,101,1.0,1.0
74262,Home away from home lodging 3 (2 Beds - 2 guests),41503603956,UNCONFIRMED,Vena,Brooklyn,East Flatbush,40.65015,-73.92803,United States,US,1,flexible,Private room,2007.0,$263,53,1.0,7.0
76053,Doorman Huge Studio Laundry 5167,27429666224,UNCONFIRMED,Jeremy & Laura,Manhattan,Hell's Kitchen,40.76748,-73.98609,United States,US,1,strict,Entire home/apt,2005.0,$169,34,30.0,1.0
96274,The Grange Place- private apartmt \r\nw/1 bedr...,93925430528,UNCONFIRMED,Mich,Manhattan,Harlem,40.82154,-73.94925,United States,US,0,moderate,Entire home/apt,2012.0,$705,141,2.0,23.0
53407,Beautiful 3 bedroom apartment!!,64686907736,UNCONFIRMED,Jenny & Jose,Brooklyn,Bedford-Stuyvesant,40.67830,-73.93799,United States,US,1,moderate,Entire home/apt,2015.0,$561,112,10.0,134.0

In [72]:
data["Price"] = data["Price"].str.replace("$","")
data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
50266,"Beautiful, sunny, spacious artist loft in LES",13621755199,VERIFIED,Jennifer,Manhattan,Lower East Side,40.71251,-73.98175,United States,US,0,moderate,Entire home/apt,2013.0,925,185,28.0,14.0
41712,Top floor apt in luxury building - lease takeover,26524403577,UNCONFIRMED,Alison,Queens,Rego Park,40.73288,-73.86438,United States,US,0,moderate,Entire home/apt,2008.0,"1,189",238,210.0,0.0
21366,"Artist room in the heart of Bushwick, Brooklyn NY",76476914206,UNCONFIRMED,Prashant,Brooklyn,Bushwick,40.69482,-73.91165,United States,US,0,moderate,Private room,2003.0,967,193,1.0,1.0
35647,Queens Palace,77059936333,VERIFIED,George & Kevin,Queens,Ditmars Steinway,40.77658,-73.90344,United States,US,1,strict,Entire home/apt,2012.0,201,40,3.0,12.0
55146,"Boutique Bedstuy Oasis, Bed & Bistro",22847571015,UNCONFIRMED,Hadiza,Brooklyn,Bedford-Stuyvesant,40.68869,-73.94618,United States,US,1,flexible,Entire home/apt,2004.0,"1,150",230,2.0,25.0
3153,Andrea's bohemian pied-a-terre,87521845584,VERIFIED,Andrea,Manhattan,Greenwich Village,40.72934,-74.00075,United States,US,1,moderate,Entire home/apt,2003.0,601,120,5.0,143.0
66368,Cozy home in Williamsburg BK,43912732024,VERIFIED,Sacha,Brooklyn,Williamsburg,40.70903,-73.96499,United States,US,0,strict,Entire home/apt,2006.0,901,180,27.0,13.0
48811,UWS Spacious Master Bedroom Sublet,71419242205,VERIFIED,Dagmara,Manhattan,Upper West Side,40.79952,-73.96003,United States,US,1,flexible,Private room,2014.0,340,68,30.0,0.0
18522,Master bedroom/private bathroom with Balcony,30045820257,UNCONFIRMED,Adam,Brooklyn,Bedford-Stuyvesant,40.68511,-73.95452,United States,US,0,flexible,Private room,2007.0,"1,183",237,3.0,5.0
99532,Charming 1 Bedroom Apartment in Greenwich Village,5298912852,UNCONFIRMED,James,Manhattan,West Village,40.73255,-74.00173,United States,US,1,flexible,Entire home/apt,2008.0,63,13,5.0,1.0

# Converting columns Construction Year and Minimum Nights from float to integer

In [75]:
data["Construction year"] = data["Construction year"].astype(np.int64)
data["Minimum nights"] = data["Minimum nights"].astype(np.int64)

data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
51397,"Have the 1st floor of a two floor duplex,",6161008998,UNCONFIRMED,Robert,Manhattan,Upper West Side,40.79455,-73.97188,United States,US,0,flexible,Private room,2018,810,162,2,156.0
31441,Cozy Brooklyn Studio with lots of light,41395810189,VERIFIED,Armine,Brooklyn,Boerum Hill,40.68944,-73.98904,United States,US,0,strict,Entire home/apt,2008,268,54,3,3.0
23690,Large/Bright room in vibrant East village,91843175586,VERIFIED,Beatrice,Manhattan,East Village,40.72507,-73.97667,United States,US,1,flexible,Private room,2013,203,41,10,17.0
63999,Charming 2 BR UES Apt (Min 30 days),67474953280,UNCONFIRMED,The Local Stay,Manhattan,Upper East Side,40.77415,-73.95534,United States,US,0,strict,Entire home/apt,2011,830,166,30,4.0
72963,WEST VILLAGE CHARM - BEST LOCATION!,93315617063,VERIFIED,Jenny,Manhattan,West Village,40.73464,-74.00084,United States,US,1,moderate,Entire home/apt,2021,280,56,1,272.0
98164,Private Room in Charming NYC Guest Suite (single),26190214181,VERIFIED,Nina,Staten Island,Clifton,40.61706,-74.08567,United States,US,1,strict,Private room,2014,346,69,2,8.0
82112,Lovely City Retreat,75050466419,UNCONFIRMED,Brooke,Queens,Elmhurst,40.74547,-73.87746,United States,US,0,strict,Private room,2012,819,164,2,103.0
81853,Charming Private Room in the heart of East Vil...,1726052427,UNCONFIRMED,Sahar,Manhattan,East Village,40.72304,-73.98089,United States,US,0,flexible,Private room,2008,"1,050",210,1,80.0
26508,Fabulous 1 bedroom in midtown Manhattan,45339717378,UNCONFIRMED,Stanley,Manhattan,Murray Hill,40.74848,-73.97564,United States,US,1,moderate,Private room,2005,178,36,30,0.0
25404,Sunny Private Room in Bed-Stuy,18464710203,VERIFIED,Carla,Brooklyn,Bedford-Stuyvesant,40.68883,-73.94821,United States,US,1,moderate,Private room,2011,709,142,3,3.0

In [76]:
data["Number of reviews"] = data["Number of reviews"].astype(np.int64)
data.sample(10)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
57421,Loft in East Williamsburg,65169601474,UNCONFIRMED,Catiana,Brooklyn,Williamsburg,40.70429,-73.93627,United States,US,1,flexible,Entire home/apt,2008,491,98,7,4
9879,Charming Classic UWS 2BR & Balcony,65821114214,VERIFIED,Clayton,Manhattan,Upper West Side,40.80193,-73.97038,United States,US,1,flexible,Entire home/apt,2013,121,24,2,18
58749,CLASSIC BEDROOM CLOSE TO MANHATTAN,9690290041,VERIFIED,Lolita,Queens,Astoria,40.76777,-73.92343,United States,US,1,flexible,Private room,2008,923,185,4,170
27316,Gorgeous Loft in Nolita with Elevator and Balc...,66229811908,VERIFIED,Richard,Manhattan,Little Italy,40.71920,-73.99650,United States,US,1,strict,Entire home/apt,2008,717,143,30,4
35532,Bronx ROOM #2 NYC-BEST DEAL,95765272892,UNCONFIRMED,Steve,Bronx,Morris Park,40.85409,-73.85032,United States,US,0,flexible,Private room,2014,358,72,5,8
91185,Nolita Bohemian Charmer,65173899275,UNCONFIRMED,Anna,Manhattan,Nolita,40.72078,-73.99473,United States,US,0,flexible,Private room,2019,890,178,10,2
70119,3 Bedroom Duplex/ 2 Baths and 2 LR,85664901643,UNCONFIRMED,Brendan,Brooklyn,Bushwick,40.68646,-73.91313,United States,US,0,strict,Entire home/apt,2013,778,156,3,38
95573,"Modern, comfy studio apartment",29700267285,UNCONFIRMED,Mo,Queens,Queens Village,40.72105,-73.73444,United States,US,1,moderate,Entire home/apt,2017,274,55,1,45
15496,Location/Charm/Comfort-Live the West Village d...,24953014562,VERIFIED,Rachel,Manhattan,West Village,40.73475,-74.00440,United States,US,1,flexible,Entire home/apt,2004,"1,186",237,3,0
15846,"Great location in NYC, clean, quiet and cozy",41926082582,VERIFIED,Grace,Brooklyn,Clinton Hill,40.68389,-73.96026,United States,US,1,strict,Private room,2004,529,106,1,15